
[client]
showErrorDetails = 'full'

[theme]
base = 'dark'

primaryColor = '#ff00f0'
backgroundColor = '#1f1f1f'
secondaryBackgroundColor = '#3a3a3f'


baseFontSize = 16
baseFontWeight = 500






#2D3748 #azulitos
#374151

#2E8B7D
#2E8B7D















