
[client]
showErrorDetails = 'full'

[theme]
base = 'dark'

primaryColor = '#303F55'
backgroundColor = '#1f1f1f'
secondaryBackgroundColor = '#3a3a3f'


baseFontSize = 16
baseFontWeight = 500










